name: Compile Assets

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm ci

      - name: Compile assets
        run: npm run production

      - name: Commit compiled files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Compile Assets
          file_pattern: public/*
