name: compile assets

on: [push]

permissions:
  contents: write

jobs:
  compile:
    uses: laravel/.github/.github/workflows/compile-assets.yml@9c15e86fffce728fb6c50ebeae24fd63e98f4d1d # main
    with:
      cmd: build
      build_path: "dist/"
      node: "21"
